import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import { Container } from "../components/Container.styles";
import { Button, FacebookButton } from "../components/Button.styles";
import { StyledLink } from "../components/Link.styles";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Button>Styled Button</Button>
        <Button variant="secondary">Styled Button</Button>
        <FacebookButton />
        <StyledLink href="/" name="hello" />
      </Container>
    </div>
  );
};
``;

export default Home;
